### PR TITLE
appveyor.yml - add VS image info to build log, Ruby 2.6 [skip travis]

### PR DESCRIPTION
**Pull request by MSP-Greg**

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Ruby trunk failed.  The build is done three times a day, and saves three files.  Every 50 to 100 builds, a file is missing.  Last build, it was the actual build archive.  I forced a build, and (of course) the three artifacts exist.

**Comment by aycabta** [comment]
I [tried 2.6 on my AppVeyor](https://ci.appveyor.com/project/aycabta/rdoc/builds/24316175) yesterday too, and it succeeded. [A previous test of master](https://ci.appveyor.com/project/ruby/rdoc/builds/24315254) also succeeded. OK, I understood what you want to do and I think it's correct. The failures on AppVeyor are just an AppVeyor's strange behavior...

I don't think much about it I just do it, and I'm going to see how it goes for a while.

**Comment by aycabta** [comment]
Tentatively, [the merge commit of this Pull Request succeeded](https://ci.appveyor.com/project/ruby/rdoc).

**Comment by MSP-Greg** [comment]
@aycabta

As mentioned, the trunk failure here in the PR was AppVeyor's strange behavior...

But, I took a look at when there were trunk build issues (both Appveyor & Travis), on 15-Feb.  I don't think the Travis build is tested, but trunk will always load a passing build, even if more recent builds are failing.  Odd thing, the failure here was when building an extension gem (racc), and the build code was looking for `defines.h` in `include/ruby-2.7.0`, but it's always been in `include/ruby-2.7.0/ruby`...

Anyway, rather than commenting out trunk, in Appveyor:

```
matrix:
  allow_failures:
    - ruby_version: _trunk
```

Feel free to ping me if there are windows issues.  Thanks for your work here and in `reline`.  It was almost passing all the readline tests last time I checked.

JFYI, on Windows, trunk, 2.5 & 2.6 include `readline.so`, but also include `rb-readline`, and have it enabled.  I look forward to replacing `rb-readline` with `reline`...

**Pull request merged**
