### PR TITLE
Improve method source toggling

### PR DESCRIPTION
**Pull request by st0012**
1. Source toggling control is now always displayed
    - If we think the buttons take too much space or are distracting, I'd be happy to accept ideas/PRs for styling improvements. But hiding them by default simply made this feature underutilized.
1. Source will be displayed directly under the method method
    - This matches rubyapi.org's behaviour and makes a more natural experience. When viewing a method with long description, users won't need to click the toggle, and then scroll all the way down to see the source.
1. Clicking the method name will not toggle the source anymore. I made this change so we can later make clicking method names link to the methods instead, like rubyapi.org and many other language documentations do.

### Before

https://github.com/user-attachments/assets/ca68c0d0-147b-421f-9e04-904366856daf

### After

https://github.com/user-attachments/assets/ea6ed17f-930a-4d4e-a298-79a535c94abc

### CODE REVIEW

**Comment by etiennebarrie** [comment]
> 3\. Clicking the method name will not toggle the source anymore. I made this change so we can later make clicking method names link to the methods instead, like rubyapi.org and many other language documentations do.

Even if we decide to keep the source toggle on the method name, I'd love to get the URL on the method name so that at least we can right-click, copy link location and share that more easily.

**Comment by st0012** [comment]
Does this look good to you? (ofc, I'm not going to make all method names green)
https://github.com/user-attachments/assets/e0ba6324-deaa-4e49-ae58-5d187796d6b1

**Review by rwstauner — APPROVED** [review]
These are great improvements, thank you!

**Comment by p8** [comment]
Maybe move the toggle to the bottom, so the toggle and the source code are closer together?
SDoc currently does this:
image

**Comment by st0012** [comment]
> I think this looks great, but I have one concern.

That's a good point. I'll think about how to avoid the confusion.

> Maybe move the toggle to the bottom, so the toggle and the source code are closer together?

Since it's been at the top for a long time, moving it to the bottom would require a huge change on users' behaviour. It's also not uncommon to see methods having very long description and examples in Ruby (e.g. `Array#[]`, `Array#fill`...etc.), and IMO being able to click and see the source toggle without scrolling further down would be a better experience.

**Comment by st0012** [comment]
To help distinguishing source code blocks and example code blocks, I ended up choosing to add `Example` label to code blocks interpreted as Ruby:


Screenshot 2024-09-12 at 12 48 20

Screenshot 2024-09-12 at 12 48 50

### Notes

- It's easier to add `Source` label but I feel it a bit repetitive when you just clicked `Source` and then see the shown block marked as `Source` again.
- Styling options are limited because the html of example code blocks are NOT controlled by the Darkfish generator but directly from RDoc. So if we were to change its html structure, it could break gems that use RDoc (e.g. SDoc)
    - Therefore, I decided to just add a new class and use its `::before` element to add the label.

**Comment by p8** [comment]
> Styling options are limited because the html of example code blocks are NOT controlled by the Darkfish generator but directly from RDoc. So if we were to change its html structure, it could break gems that use RDoc (e.g. SDoc)

You should be able to change the background of the source with the following:
```css
.method-source-code pre {
  background: #ebead5;
}
```

image

**Comment by p8** [comment]
Looks great!

**Comment by colby-swandale** [comment]
I have a couple of items: 

* The various yellows on the page doesn't seem to blend well together and makes the page distracting. Could we tweak the colors a bit to make it easier on the eyes?

Screenshot 2024-10-03 at 11 45 23 PM

* The arrow/collaspe icon next to the `Source` link is a bit confusing to me. It comes across as a play button for audio/video nearly everytime I look at It. Could we look to remove it and give the link an active/hover state?

**Comment by st0012** [comment]
I made their color match and change it to fit the current color scheme better:

Screenshot 2024-10-03 at 17 25 23

I'm not happy with the color but I think further improvements on it belongs to #1164

> Could we look to remove it and give the link an active/hover state?

I think this is more subject to personal taste? To me it's a clear sign that it's a `details` element and I can expand it. It's the default triangle that comes with the element and it's in the sidebar too.

I don't mind it being redesigned later but I don't see the value of introducing yet another UI effect to remind users it's click/expandable.

**Comment by st0012** [comment]
@colby-swandale Can you give this another look please?

**Review by colby-swandale — APPROVED** [review]

**Pull request merged**
