### PR TITLE
Added missing _sidebar_toggle.rhtml

### PR DESCRIPTION
**Pull request by ishe-ua**
Add missing file

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
This file was added in #1157 - but not added to the gemspec for inclusion, and this PR fixes that.

https://github.com/ruby/rdoc/blob/master/lib/rdoc/generator/template/darkfish/_sidebar_toggle.rhtml

**Review by st0012 — APPROVED** [review]

**Comment by st0012** [comment]
Thank you!

**Comment by zzak** [comment]
Why not just use a glob?

**Comment by st0012** [comment]
@zzak doing that in https://github.com/ruby/rdoc/pull/1212

**Pull request merged**
