### PR TITLE
Add HTML fragment references for constants

### PR DESCRIPTION
**Pull request by p8**
In large libraries with a lot of constants (Rails for example), it would be nice to deep link to these constants.

### CODE REVIEW

**Comment by p8** [comment]
It would be nice if we could deeplink to the following constants in the Rails API docs:
image
https://api.rubyonrails.org/classes/ActionDispatch/Http/Cache/Response.html

It helps when trying to communicate the values of these constants with others.
For example I could share the `DATE` constant here:
https://api.rubyonrails.org/classes/ActionDispatch/Http/Cache/Response.html#constant- ActionDispatch::Http::Cache::Response::DATE

**Comment by nobu** [comment]
> https://api.rubyonrails.org/classes/ActionDispatch/Http/Cache/Response.html

Is that page generated with RDoc?

**Comment by p8** [comment]
Yes. It uses https://github.com/rails/sdoc which is built on top of RDoc.

**Comment by nobu** [comment]
It seems a role of views.
Shouldn't it be done in template files?

**Comment by nobu** [comment]
SDoc doesn't seem adding `id` to constants. https://github.com/rails/sdoc/blob/4d1c71adff9c5f0d4fcf8c50eab29f4bcf301abf/lib/rdoc/generator/template/rails/_context.rhtml#L93C1
Shouldn't it be fixed first?

**Pull request closed without merging**
