### PR TITLE
Prefer require_relative

### PR DESCRIPTION
**Pull request by marcandre**
Small but free speed gain by using `require_relative` instead of `require`

### CODE REVIEW

**Comment by aycabta** [comment]
@marcandre I'm considering this but I need a performance report. I'll reject any optimizations without a performance report.

**Comment by aycabta** [comment]
And please add the report to the commit comment.

Example: https://github.com/ruby/rdoc/pull/640/commits/818ee979e02151885b4ae769b9f87b8f6b5f1802

**Comment by marcandre** [comment]
@aycabta I'm considering your request but I need a single example or argument whereby `require_relative` would not be faster, safer and more expressive than `require`. I'll reject your request without that.

**Comment by nobu** [comment]
I agree that `require_relative` will be faster (never slower at least) than `require`.
And curious how it get faster depending on the length of `$:`.

**Comment by ioquatix** [comment]
We don't need performance report for this. It's simply better to prefer `require_relative`. So, if you update the PR, I will merge it.

**Comment by marcandre** [comment]
@ioquatix PR rebased

**Comment by hsbt** [comment]
It's totally maintainers who are @aycabta 's convenience.

**Comment by marcandre** [comment]
Ping @aycabta

**Review by ioquatix — APPROVED** [review]

**Pull request merged**
