### PR TITLE
Correction to include regexp_handling in list of loaded files

### PR DESCRIPTION
**Pull request by poloka**
With the update to 6.1.0, a new file was added `regexp_handling.rb` but it was not added to the specification for loading upon including gem into project.

### CODE REVIEW

**Comment by ChapterHouse** [comment]
+1

**Comment by aycabta** [comment]
Thank you, this problem(https://github.com/ruby/rdoc/issues/681) is my mistake. I'll release 6.1.1 right now.

**Comment by aycabta** [comment]
Released!
https://rubygems.org/gems/rdoc

Thanks a lot to you, I realized the problem with your report and was able to quickly measures.

**Comment by poloka** [comment]
Awesome!  Thanks @aycabta for the quick turnaround.

**Pull request merged**
