### PR TITLE
appveyor.yml - correct case in paths, use trunk

### PR DESCRIPTION
**Pull request by MSP-Greg**
This can cause very odd issues, seemingly coming out of nowhere.  I had the mistake in some repos also...

2nd commit uses trunk.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Test times should be much faster, as Appveyor does not set a default clone depth, so the `git clone` was grabbing everything.  I set it to match Travis, which is 50.

Sorry about the extra tests, this is passing in my fork (multiple times), but 2.6 isn't passing here.  I also got interrupted when I wanted to merge two commits, didn't, and pushed...

I'll raise an issue with Appveyor about 2.6.

**Comment by MSP-Greg** [comment]
Done.  Forgive me, might I inquire why?

**Comment by aycabta** [comment]
Unfortunately, AppVeyor doesn't support 2.6 yet...

**Comment by MSP-Greg** [comment]
@aycabta

Appveyor does support 2.6.  It is an Appveyor issue, but the problem is only with older (?) VS images.  The image can be set in the UI, or in the yaml.  I added a newer image to the yaml, and it works fine (2.6.1)

See
https://ci.appveyor.com/project/ruby/rdoc/builds/24219700/job/fc8725pb2fc6hv2m
and
https://ci.appveyor.com/project/ruby/rdoc/builds/24219700/job/u95t56kk7aksf5y1#L98

They will updating 2.4, 2.5, & 2.6 sometime in the near future.

JFYI, you may (from time to time) find CI Ruby version summaries I run on CRON sessions helpful:

https://travis-ci.org/MSP-Greg/travis-ruby
https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby

https://travis-ci.org/MSP-Greg/travis-ruby

**Pull request merged**
