### PR TITLE
Fix backtick handling

### PR DESCRIPTION
**Pull request by aycabta**

### CODE REVIEW

**Comment by aycabta** [comment]
This depends on #469.

**Comment by hsbt** [comment]
`test_accept_verbatim_escape_in_string` and `test_class_tokenize_string_with_escape` are not related this pull request. They are needless tests?

**Comment by aycabta** [comment]
Sorry, it's my mistake in merging yesterday. I fixed and `push -f`ed.

**Comment by hsbt** [comment]
Thanks! I confirmed.

**Pull request merged**
